#!/bin/bash

get_record_info() {
    local domain=$1
    local subdomain=$2
    local record_type=$3

    dig_output=$(dig "${subdomain}.${domain}" | awk '/ANSWER SECTION:/ {getline; print}')
    
    if [ -n "${dig_output}" ]; then
        echo "The subdomain ${subdomain} is a ${record_type} record and points to ${dig_output}"
    else
        echo "No information found for ${subdomain}.${domain}"
    fi
}

audit_domain() {
    local domain=$1
    
    get_record_info "${domain}" "www" "A"
    get_record_info "${domain}" "lb-01" "A"
    get_record_info "${domain}" "web-01" "A"
    get_record_info "${domain}" "web-02" "A"
}

audit_subdomain() {
    local domain=$1
    local subdomain=$2

    get_record_info "${domain}" "${subdomain}" "A"
}

main() {
    local domain=$1
    local subdomain=$2

    if [ -z "${subdomain}" ]; then
        audit_domain "${domain}"
    else
        audit_subdomain "${domain}" "${subdomain}"
    fi
}

# Check if the required arguments are provided
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

main "$@"
